namespace Sam4sTillSystem.Enum
{
    public enum Screen
    {
        BlankScreen,
        CancelOrderScreen,
        ChangeDueScreen,
        CloudFunctionsScreen,
        CloudUplinkScreen,
        CloudLinkStatusScreen,
        DailyStatsScreen,
        DailyItemSectionBreakdownScreen,
        DiscountScreen,
        EnterOrderDiscountScreen,
        FunctionScreen,
        ManualEntryAmountScreen,
        ManualEntryScreen,
        NoSaleActivationsScreen,
        OptionalItemsScreen,
        OrderDiscountScreen,
        OrderSummaryScreen,
        PaymentScreen,
        PayByCardScreen,
        ItemOptionsScreen,
        ItemSelect,
        ItemSummaryScreen,
        RefundScreen,
        TableSelect,
        PrinterSettingsScreen,
        SavedOrdersAddNewScreen
    }
}
